### ISSUE TITLE
Admin create master

### ISSUE THREAD

**Issue by michael-mckenna** [Trivolution/MugClub-Android#30]
Have a screen with a "create master code button" (see ios layout example)
Then, have that lead to the scanner view.
Upon scan, it will use the createMasterCode function in the ParseAPI() class

**Comment by Joshua-Wright** [comment]
create the master code class instance
download it from parse
put it in realm

do not generate the QR code

**Comment by michael-mckenna** [comment]
After you download the master code, all you have to do is call
MasterCode.save(object.getString("qrString")
